/**
 * 檔案：src/app/ip/en/page.tsx  →  路由 /ip/en
 * 角色：前端層 — 智慧財產權宣告（英文版，內容與 /ip 對應）
 */
import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Intellectual Property Notice',
  description:
    'Copyright and usage terms for the AI-CAT website, source code, mark, and content.',
  alternates: {
    canonical: '/ip/en',
    languages: { 'zh-Hant': '/ip', en: '/ip/en' },
  },
};

const CONTACT = 'icguanyu@gmail.com';

export default function IpEnPage() {
  return (
    <main className="legal">
      <div className="legal-nav">
        <Link className="back" href="/">
          ← Home
        </Link>
        <Link className="back" href="/ip">
          中文
        </Link>
      </div>
      <h1>Intellectual Property Notice</h1>
      <p className="updated">Last updated: 2026-09-08</p>

      <p>
        This is an English translation for reference. In case of any discrepancy
        between this version and the{' '}
        <Link href="/ip">Traditional Chinese version</Link>, the Chinese version
        prevails.
      </p>

      <h2>1. Copyright</h2>
      <p>
        © 2026 icguanyu. All rights reserved. The source code, interface and
        visual design, documentation, assessment scenario bank, and prompt logic
        of this website, &ldquo;AI-CAT — AI Competency Assessment Tool&rdquo;,
        are the exclusive property of the copyright holder.
      </p>
      <p>
        This project is <strong>not open-source software</strong>, and no
        license, express or implied, is granted. Without the copyright
        holder&rsquo;s prior written consent, it may not be reproduced,
        distributed, publicly transmitted, adapted, rented, or used for
        commercial purposes in any form.
      </p>

      <h2>2. Name and mark</h2>
      <p>
        The &ldquo;AI-CAT&rdquo; name, the cat logomark, and related visual
        identity are identifiers of the Service. They may not be used in any way
        likely to cause confusion, or to imply association with, sponsorship by,
        or endorsement from the Service.
      </p>

      <h2>3. Your input</h2>
      <p>
        The text you enter during an assessment remains yours. As necessary to
        provide the Service, you grant the Service a non-exclusive,
        royalty-free license to process that content in order to: send it to AI
        models to generate replies and scoring, generate your competency report,
        and retain assessment records under your account. See the{' '}
        <Link href="/privacy/en">Privacy Policy</Link> for details.
      </p>

      <h2>4. Third-party materials</h2>
      <ul>
        <li>
          AI models and their output: governed by OpenAI&rsquo;s terms of
          service and usage policies.
        </li>
        <li>
          Fonts: Noto Sans TC and IBM Plex Mono, licensed under the SIL Open
          Font License 1.1.
        </li>
      </ul>

      <h2>5. Disclaimer for AI-generated content</h2>
      <p>
        The competency report, level, &ldquo;L5 exemplar&rdquo;, and similar
        content are generated by AI models and may be incomplete or incorrect.
        They are for learning and self-reference only and{' '}
        <strong>
          do not constitute professional advice or any form of warranty
        </strong>
        .
      </p>

      <h2>6. Prohibited conduct</h2>
      <p>When using this website, you must not:</p>
      <ul>
        <li>
          Reverse engineer, disassemble, or decompile the Service&rsquo;s source
          code or compiled programs, or otherwise obtain or reconstruct
          non-public source code, algorithms, or prompt logic.
        </li>
        <li>
          Crack, circumvent, or disable any technical protection measure, access
          control, authentication, or rate-limiting mechanism.
        </li>
        <li>
          Introduce, distribute, or execute malware, backdoors, viruses,
          scripts, or any code capable of interfering with, damaging, or
          tampering with the Service, its data, or other users&rsquo; rights.
        </li>
        <li>
          Access the Service&rsquo;s servers, database, accounts, or non-public
          data without authorization, or conduct penetration testing,
          vulnerability scanning, stress testing, or other security testing
          without prior written consent.
        </li>
        <li>
          Use automated programs to scrape content at scale, misuse the API, or
          circumvent usage limits by any means.
        </li>
        <li>
          Remove, obscure, or alter any copyright notice, this Notice, or other
          rights markings.
        </li>
      </ul>

      <h2>7. Legal liability and reservation of rights</h2>
      <p>
        The conduct listed in the preceding section may violate the Copyright
        Act, the Trade Secrets Act, the offenses against computer security
        chapter of the Criminal Code (Articles 358 to 363), and other applicable
        laws of the Republic of China (Taiwan), and may give rise to liability
        for damages under the Civil Code.
      </p>
      <p>
        The copyright holder <strong>reserves all rights to pursue legal
        action</strong>. For any unauthorized reproduction, distribution,
        cracking, tampering, malicious attack, or code misuse, the copyright
        holder may pursue the offender&rsquo;s civil and criminal liability
        according to law; the offender shall further compensate all resulting
        losses, including without limitation: service interruption, repair and
        reconstruction costs, operational and financial losses, reputational
        harm, and investigation, litigation, and attorney&rsquo;s fees.
      </p>
      <p>
        This Notice does not grant, and shall not be construed as granting, any
        right to circumvent the above restrictions. Even where part of the
        Service&rsquo;s code can be viewed in the browser for technical reasons,
        this does not mean the copyright holder waives its rights or consents to
        its reproduction, adaptation, or reuse.
      </p>

      <h2>8. Infringement notice and contact</h2>
      <p>
        If you believe any content on this website infringes your rights, or if
        you have questions about this Notice, email{' '}
        <a href={`mailto:${CONTACT}`}>{CONTACT}</a>.
      </p>

      <p className="legal-footer">
        <Link href="/privacy/en">Privacy Policy</Link> ·{' '}
        <Link href="/">Home</Link>
      </p>
    </main>
  );
}
